//let idade = 5;
//console.log(idade);
//let Altura = 180;
//console.log(Altura);
let nome = "Joao Ricardo";
console.log(nome);
let sobrenome = "Soares";
console.log(sobrenome);
let cidade = "niteroi";
console.log(cidade);